integration:
  default: local

  local:
    api:
      url: http://localhost:5170
    folders:
      response: ApiResponses
      requestBody: TestCase/Request
      responseBody: TestCase/Response
    filter:
      strategy: tags
      envVariable: TEST_TAGS

  qa:
    api:
      url: ${QA_API_URL}
    auth:
      type: bearer
      token: ${QA_API_TOKEN}
    folders:
      response: ApiResponses
      requestBody: TestCase/Request
      responseBody: TestCase/Response
    filter:
      strategy: tags
      envVariable: TEST_TAGS
