// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Curated by hand instead of autogenerated, mirroring the grouping the repository's own
 * README doc tables already use (Getting Started / Writing Tests / Assertions and Data Flow /
 * Suite Startup Modes + Auth / Operations and Extension) rather than a flat alphabetical list.
 *
 * Every category here holds 2+ docs on purpose: a single-item category still gets a
 * generated-index page, and Infima's card grid lays one card out lopsided with dead space
 * beside it. That's why "Startup & Auth" merges app-launcher (startup) and auth-profiles
 * (auth) into one category instead of two one-item ones.
 *
 * doc-strategy.md and Package.Readme.md are excluded from the docs build entirely (see
 * docusaurus.config.js `docs.exclude`), not just left off this list.
 *
 * @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Get Started',
      link: {
        type: 'generated-index',
        description: 'Wire up a suite with SuiteBootstrapper, and see what happens at runtime across component, integration, and command-mode suites.',
      },
      items: ['suite-setup', 'test-execution-flow'],
    },
    {
      type: 'category',
      label: 'Writing Tests',
      link: {
        type: 'generated-index',
        description: 'The test definition DSL -- fields, mock interactions, GraphQL requests, and filtering which tests run.',
      },
      items: ['test-file-format', 'mock-interactions', 'graphql-support', 'test-filtering'],
    },
    {
      type: 'category',
      label: 'Assertions & Data Flow',
      link: {
        type: 'generated-index',
        description: 'Matchers for dynamic fields, extracting values from responses, and the dependency graph that governs which tests run in what order.',
      },
      items: ['matchers-and-patterns', 'variable-extraction-and-injection', 'test-dependency-graph'],
    },
    {
      type: 'category',
      label: 'Startup & Auth',
      link: {
        type: 'generated-index',
        description: 'Out-of-process startup for any language via AppLauncher, and declarative auth for bearer, OAuth2, and API key flows.',
      },
      items: ['app-launcher', 'auth-profiles'],
    },
    {
      type: 'category',
      label: 'Operations & Extension',
      link: {
        type: 'generated-index',
        description: 'Reading failure output, extension points for custom logging/processing/matchers, and the AI agent skills that drive ConfIT.',
      },
      items: ['failure-output', 'extending-confit', 'ai-skills'],
    },
  ],
};

export default sidebars;
